name: create-release

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  build-and-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Get project version
        id: get_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Check for branch name collision
        id: check_collision
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="${{ steps.get_version.outputs.VERSION }}"

          if git ls-remote --heads origin "$TAG_NAME" | grep -q "$TAG_NAME"; then
            echo "::error::Branch name collision detected! A branch named '$TAG_NAME' already exists."
            echo "Please delete the branch '$TAG_NAME' manually or update the version in pom.xml."
            exit 1
          else
            echo "No conflicting branch found. Proceeding..."
          fi

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn -pl api clean install && mvn -pl demo clean package
          TAG_NAME="${{ steps.get_version.outputs.VERSION }}"
          
          cat <<EOF > release-note
          **This release is accompanied by two attached files.**  
          - custom-crafter-api-$TAG_NAME.jar: **API**
          - custom-crafter-api-**demo**-$TAG_NAME.jar: **Demo plugin**
            
          EOF
          sed -n '2,${/^# /{:a;n;/^# /q;p;ba}}' CHANGELOG.md >> release-note
          
          gh release create "$TAG_NAME" \
            api/target/custom-crafter-api-$TAG_NAME.jar \
            demo/target/custom-crafter-api-demo-$TAG_NAME.jar \
            --target master \
            --title "v$TAG_NAME release" \
            --notes-file release-note \
            --draft